#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/Lesson_13_Assignment_Regression_Challenge.R /autograder/source/Lesson_13_Assignment_Regression_Challenge.R

cd /autograder/source


Rscript grade_one_submission.r 
